// The site's inline editor (O55b) - generated by engine/build_pages.py, do not edit in place.
const BASKET_KEY = "gg-site-basket";
const armed = () => { try { return sessionStorage.getItem("gg-site-editing") === "1"; } catch { return false; } };
const basket = () => { try { const b = JSON.parse(localStorage.getItem(BASKET_KEY) || "{}"); return { siteCopy: b.siteCopy || {}, explainers: b.explainers || {} }; } catch { return { siteCopy: {}, explainers: {} }; } };
const saveBasket = (b) => { try { localStorage.setItem(BASKET_KEY, JSON.stringify(b)); } catch { /* private mode */ } };
const basketSize = (b) => Object.keys(b.siteCopy).length + Object.keys(b.explainers).length;

async function config() {
  try {
    const r = await fetch(new URL("web/backend.json", import.meta.url));
    if (!r.ok) return null;
    const b = await r.json();
    return b.url && b.anonKey ? { url: b.url.replace(/\/+$/, ""), anonKey: b.anonKey } : null;
  } catch { return null; }
}
function session() {
  try { const raw = localStorage.getItem("gg-sync-session"); return raw ? JSON.parse(raw) : null; } catch { return null; }
}
async function postFn(payload) {
  const cfg = await config(); const ses = session();
  if (!cfg || !ses) return null;
  try {
    const res = await fetch(cfg.url + "/functions/v1/content-pr", {
      method: "POST",
      headers: { "content-type": "application/json", "authorization": "Bearer " + ses.access_token, "apikey": cfg.anonKey },
      body: JSON.stringify(payload),
    });
    return { status: res.status, body: await res.json().catch(() => ({})) };
  } catch { return null; }
}

const el = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text !== undefined) n.textContent = text; return n; };
let started = false, pins = {}, serverCopy = {};

const CHROME_CSS = `
body.sed-editing [data-copy], body.sed-editing [data-explainer] { outline: 2px dashed var(--accent); outline-offset: 3px; cursor: pointer; }
#sedpill { position: fixed; bottom: 1rem; left: 50%; translate: -50%; z-index: 60; display: flex; gap: .15rem; align-items: center;
  background: var(--accent); color: #fff; border-radius: 999px; padding: .25rem .45rem; box-shadow: 0 2px 10px rgba(0,0,0,.3); white-space: nowrap; }
#sedpill .lbl { font: 600 .72rem ui-monospace, monospace; letter-spacing: .04em; text-transform: uppercase; padding: 0 .35rem; opacity: .85; }
#sedpill button { border: 0; cursor: pointer; background: transparent; color: #fff; font: 600 .95rem inherit; min-height: 36px; padding: 0 .55rem; border-radius: 999px; }
#sedpill button:hover { background: rgba(255,255,255,.14); }
#sedpill .cnt { background: rgba(255,255,255,.18); }
#seddrawer { position: fixed; inset: auto 0 0 0; z-index: 61; max-height: 72vh; overflow-y: auto; background: var(--surface); color: var(--text);
  border-top: 1px solid var(--divider); border-radius: .8rem .8rem 0 0; padding: .7rem .9rem 1rem; box-shadow: 0 -6px 24px rgba(0,0,0,.25); }
#seddrawer .k { margin: 0 0 .4rem; font: 600 .85rem ui-monospace, monospace; }
#seddrawer textarea { width: 100%; padding: .5rem .6rem; border: 1px solid var(--divider); border-radius: .4rem; background: var(--bg); color: var(--text); font: .95rem/1.5 inherit; resize: vertical; }
#seddrawer .pin { margin: .35rem 0 0; font-size: .8rem; color: var(--accent); }
#seddrawer .note { margin: .35rem 0 0; font-size: .8rem; color: var(--muted); }
#seddrawer .row { display: flex; gap: .5rem; justify-content: flex-end; margin-top: .7rem; }
#seddrawer .btn { display: inline-flex; align-items: center; min-height: 44px; background: var(--accent); color: #fff; border: 0; border-radius: 999px; padding: 0 1rem; font: 600 .95rem inherit; cursor: pointer; }
#seddrawer .btn.ghost { background: transparent; color: var(--accent); border: 1px solid var(--divider); }
#seddrawer .btn:disabled { opacity: .6; cursor: default; }
#seddrawer .item { display: flex; align-items: center; justify-content: space-between; gap: .6rem; border-bottom: 1px solid var(--divider); padding: .35rem 0; font-size: .95rem; }
#seddrawer .item .ik { font: 600 .85rem ui-monospace, monospace; }
#seddrawer .item small { color: var(--muted); }
#seddrawer .item .x { border: 0; background: transparent; color: var(--muted); cursor: pointer; font-size: 1.1rem; min-width: 44px; min-height: 44px; }
#seddrawer .status a { color: var(--accent); }
`;

function closeDrawer() { const d = document.getElementById("seddrawer"); if (d) d.remove(); }
function drawer(title) {
  closeDrawer();
  const d = el("div"); d.id = "seddrawer";
  d.appendChild(el("p", "k", title));
  document.body.appendChild(d);
  return d;
}

function applyLive(key, v) {
  for (const n of document.querySelectorAll('[data-copy="' + key + '"]')) n.textContent = v;
}
function applyBasket() {
  const b = basket();
  for (const k of Object.keys(b.siteCopy)) applyLive(k, b.siteCopy[k]);
}

function renderPill() {
  const old = document.getElementById("sedpill"); if (old) old.remove();
  const pill = el("div"); pill.id = "sedpill";
  const n = basketSize(basket());
  const cnt = el("button", "cnt", n === 1 ? "1 change" : n + " changes");
  cnt.type = "button"; cnt.addEventListener("click", basketDrawer);
  const done = el("button", "", "Done");
  done.type = "button";
  done.addEventListener("click", () => { try { sessionStorage.removeItem("gg-site-editing"); } catch { /* fine */ } location.reload(); });
  pill.append(el("span", "lbl", "Editing this site"), cnt, done);
  document.body.appendChild(pill);
}

function copyDrawer(key) {
  const b = basket();
  const current = b.siteCopy[key] !== undefined ? b.siteCopy[key]
    : (serverCopy[key] !== undefined ? serverCopy[key]
      : (document.querySelector('[data-copy="' + key + '"]') || {}).textContent || "");
  const d = drawer(key);
  const area = el("textarea"); area.rows = current.length > 90 ? 4 : 2; area.value = current;
  d.appendChild(area);
  if (key in pins) d.appendChild(el("p", "pin", "Held by a check - proposing this edit opens a PR that stays red until a session moves its test."));
  d.appendChild(el("p", "note", "The page updates as you type - on this device only, until the PR merges."));
  area.addEventListener("input", () => applyLive(key, area.value));
  const row = el("div", "row");
  const revert = el("button", "btn ghost", "Revert"); revert.type = "button";
  revert.addEventListener("click", () => {
    applyLive(key, serverCopy[key] !== undefined ? serverCopy[key] : current);
    const bb = basket(); delete bb.siteCopy[key]; saveBasket(bb);
    renderPill(); closeDrawer();
  });
  const keep = el("button", "btn", "Keep in changes"); keep.type = "button";
  keep.addEventListener("click", () => {
    const v = area.value;
    if (!v.trim()) return; // an emptied string is a revert, not an edit
    const bb = basket();
    if (v === serverCopy[key]) delete bb.siteCopy[key]; else bb.siteCopy[key] = v;
    saveBasket(bb); renderPill(); closeDrawer();
  });
  row.append(revert, keep); d.appendChild(row);
  area.focus();
}

function explainerDrawer(slug) {
  const d = drawer("explainer: " + slug);
  const area = el("textarea"); area.rows = 12; area.value = "Loading…"; area.disabled = true;
  d.appendChild(area);
  d.appendChild(el("p", "note", "The markdown behind this page. The rendered page updates when the PR merges and the site rebuilds."));
  const row = el("div", "row");
  const cancel = el("button", "btn ghost", "Cancel"); cancel.type = "button";
  cancel.addEventListener("click", closeDrawer);
  const keep = el("button", "btn", "Keep in changes"); keep.type = "button"; keep.disabled = true;
  keep.addEventListener("click", () => {
    if (area.value.trim()) { const bb = basket(); bb.explainers[slug] = area.value; saveBasket(bb); }
    renderPill(); closeDrawer();
  });
  row.append(cancel, keep); d.appendChild(row);
  const prior = basket().explainers[slug];
  if (prior !== undefined) { area.value = prior; area.disabled = false; keep.disabled = false; return; }
  postFn({ mode: "explainer-read", slug }).then((r) => {
    if (r && typeof r.body.markdown === "string") { area.value = r.body.markdown; area.disabled = false; keep.disabled = false; }
    else area.value = r ? "Could not load: " + (r.body.error || r.status) : "Network error.";
  });
}

function basketDrawer() {
  const b = basket();
  const n = basketSize(b);
  const d = drawer(n === 1 ? "1 change" : n + " changes");
  const list = el("div"); d.appendChild(list);
  const item = (label, sub, remove) => {
    const row = el("div", "item");
    const left = el("span");
    left.appendChild(el("span", "ik", label));
    left.appendChild(document.createElement("br"));
    left.appendChild(el("small", "", sub));
    const x = el("button", "x", "×"); x.type = "button";
    x.addEventListener("click", () => { remove(); renderPill(); closeDrawer(); if (basketSize(basket())) basketDrawer(); });
    row.append(left, x); list.appendChild(row);
  };
  for (const k of Object.keys(b.siteCopy)) item(k, '"' + b.siteCopy[k].slice(0, 44) + '"', () => {
    applyLive(k, serverCopy[k] !== undefined ? serverCopy[k] : "");
    const bb = basket(); delete bb.siteCopy[k]; saveBasket(bb);
  });
  for (const slug of Object.keys(b.explainers)) item("explainer: " + slug, "edited text", () => {
    const bb = basket(); delete bb.explainers[slug]; saveBasket(bb);
  });
  if (!n) list.appendChild(el("p", "note", "Nothing kept yet - tap any outlined element to edit it."));
  const status = el("p", "status");
  const row = el("div", "row");
  const back = el("button", "btn ghost", "Keep editing"); back.type = "button";
  back.addEventListener("click", closeDrawer);
  const propose = el("button", "btn", "Propose all as one PR"); propose.type = "button";
  propose.disabled = n === 0;
  propose.addEventListener("click", async () => {
    propose.disabled = true;
    status.textContent = "Opening a pull request…";
    const bb = basket();
    const r = await postFn({ mode: "changeset", siteCopy: bb.siteCopy, explainers: bb.explainers });
    status.replaceChildren();
    if (r && r.body.prUrl) {
      status.append("Pull request opened - nothing is live until you merge it. ");
      const a = el("a", "", "Review the PR"); a.href = r.body.prUrl; a.target = "_blank"; a.rel = "noreferrer";
      status.appendChild(a);
      saveBasket({ siteCopy: {}, explainers: {} });
      renderPill();
    } else if (r && r.status === 403) {
      status.textContent = "This account is not the maintainer - the server refused the write.";
      propose.disabled = false;
    } else {
      status.textContent = r ? "Could not open the PR: " + (r.body.error || r.status) : "Network error.";
      propose.disabled = false;
    }
  });
  row.append(back, propose);
  d.append(status, row);
}

function intercept(e) {
  const t = e.target;
  if (!t || !(t instanceof Element)) return;
  if (t.closest("#seddrawer") || t.closest("#sedpill")) return; // the chrome itself works normally
  const exp = t.closest("[data-explainer]");
  const hit = t.closest("[data-copy]");
  if (!exp && !hit) return;
  e.preventDefault();
  e.stopPropagation();
  if (hit) copyDrawer(hit.getAttribute("data-copy"));
  else explainerDrawer(exp.getAttribute("data-explainer"));
}

async function boot(loud) {
  if (started) return;
  const r = await postFn({ mode: "copy-read", copyFile: "site" });
  if (!r || !r.body.copy) {
    // Arming is passive on an armed session's navigation, so a quiet failure must stay quiet -
    // but an EXPLICIT #edit entry gets told what happened, same register as the app's editor.
    if (loud) alert(r && r.status === 403
      ? "This account is not the maintainer - editing is maintainer-only."
      : "Editing needs the backend and a signed-in session (sign in from the app first).");
    return;
  }
  started = true;
  try { sessionStorage.setItem("gg-site-editing", "1"); } catch { /* fine */ }
  try { localStorage.setItem("gg-editor", "1"); } catch { /* fine */ }
  pins = r.body.pins || {};
  serverCopy = r.body.copy || {};
  const style = document.createElement("style"); style.textContent = CHROME_CSS; document.head.appendChild(style);
  document.body.classList.add("sed-editing");
  applyBasket();
  renderPill();
  document.addEventListener("click", intercept, true);
}

if (location.hash === "#edit") boot(true);
else if (armed()) boot(false);
window.addEventListener("hashchange", () => { if (location.hash === "#edit") boot(true); });
